# Generated by Django 4.2.10 on 2024-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_userprofile_image_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='password',
            field=models.CharField(max_length=1024),
        ),
    ]
