# Generated by Django 4.2.10 on 2024-04-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_gameroom_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='host',
            field=models.CharField(max_length=1024),
        ),
    ]
