# Generated by Django 4.2.10 on 2024-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_matchhistory_opponent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='host',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='opponent_name',
            field=models.CharField(max_length=100),
        ),
    ]
