version : '3'

services :
  django :
    container_name : app
    image : app
    pull_policy : never
    build : ./ft_oop_Backend
    ports :
      - 8000:8000
    volumes :
      - oop-volume:/app/src

volumes:
  oop-volume:
    driver: local
    driver_opts:
      device: /Users/parksuhwan/Desktop/About42/oop_Backend/ft_oop_Backend
      type: none
      o: bind