# Generated by Django 4.2.10 on 2024-02-07 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intra_name', models.CharField(max_length=10)),
                ('picture', models.CharField(max_length=255)),
                ('total_win', models.IntegerField(default=0)),
                ('total_lose', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=64)),
                ('room_type', models.IntegerField(default=0)),
                ('limits', models.IntegerField(default=0)),
                ('passWord', models.CharField(max_length=12)),
                ('host', models.CharField(max_length=10)),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='models.user')),
            ],
        ),
    ]
