# Generated by Django 4.2.10 on 2024-02-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_gameroom_guests_user_game_room_matchhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchhistory',
            old_name='date',
            new_name='match_date',
        ),
    ]
